### ISSUE TITLE
Test suite fails with Catalyst 5.90082 and later

### ISSUE THREAD

**Issue by eserte** [markwellis/plack-middleware-debug-catalyststash#1]
See:
- http://matrix.cpantesters.org/?dist=Plack-Middleware-Debug-CatalystStash
- http://analysis.cpantesters.org/solved?distv=Plack-Middleware-Debug-CatalystStash-0.001002

**Comment by simbabque** [comment]
Actually not only the test suite fails. The whole thing does not work any more.

**Comment by markwellis** [comment]
Is this still an issue with Catalyst > 5.90100 as there was a fix committed

https://github.com/perl-catalyst/catalyst-runtime/commit/5e7e6b272a9e1b8bf1c401dd3a607fc851c43cc7

**Comment by eserte** [comment]
Confirmed — no failures anymore with Catalyst ≥ 5.90100:
http://analysis.cpantesters.org/solved?distv=Plack-Middleware-Debug-CatalystStash-0.001002#mod%3ACatalyst
